  describe('has application management functions', function () {
    it('`matrix list apps`')
    it('`matrix search`')
    // it('`matrix search -s`')
    it('`matrix install`')
    // it('`matrix install sensor`')
    it('`matrix uninstall`')
    // it('`matrix update`')
    it('`matrix start`')
    it('`matrix stop`')
    it('`matrix set config`')
    it('`matrix set config app`')
    it('`matrix set config app key`')
    it('`matrix set config app key=value`')
  })

  describe('has application development functions', function(){
    it('`matrix create`')
    it('`matrix deploy`')
    it('`matrix trigger`')
    it('`matrix log`')
  })
